### ISSUE TITLE
StateEngine availability exception

### ISSUE THREAD

**Issue by AAverin** [thefuntastic/Unity3d-Finite-State-Machine#15]
I keep getting this exception that StateEngine is missing: Please make sure StateEngine is also present on any StateBehaviour objects.

I'm calling Initialize<States>(); in Awake of my GameObject, that inherits StateBehaviour.
Debugging a project, somehow I don't see debugger stopping on 

    _stateMachine = GetComponent<StateEngine>();

line. For some reason it goes directly to throwing an exception.

I'm no Unity expert, and might be that my setup is wrong or something, but have no idea why this is happening.
Could it be that some kind of update is required for latest unity, or [RequireComponent(typeof(StateEngine))] stopped working for some reason?

**Comment by AAverin** [comment]
Debugging shows that following line returns null

    					_stateMachine = GetComponent<StateEngine>();

**Comment by nkoufou** [comment]
That's strange, can you confirm that your GameObject has both the StateBehaviour derived component and the StateEngine component attached? If StateEngine component is attached to the GameObject do you get a required warning when trying to remove it?

**Comment by AAverin** [comment]
Should I directly put StateEngine object to GameObject manually in the Editor?
I dont think it's mentioned in the Usage section of the library

**Comment by nkoufou** [comment]
You shouldn't have to, the RequireComponent attribute should attach the Component for you in the editor automatically. Try manually adding StateEngine and see what happens

**Comment by AAverin** [comment]
no exception when attached manually. looks like RequireComopnent isnt working

**Comment by nkoufou** [comment]
That is bizarre, I am not aware of any particular version of Unity that had this functionality broken. Do you now have both the StateBehaviour and the StateEngine components attached to your GameObject?

**Comment by AAverin** [comment]
Yes

**Comment by nkoufou** [comment]
Is the state machine now initializing properly?

**Comment by AAverin** [comment]
Judging by the log output that I have added to property getter - yes, it does.
Unity API doesn't mention any changes to RequireComponent, so in theory it should work.
http://docs.unity3d.com/ScriptReference/RequireComponent.html

**Comment by nkoufou** [comment]
Weird, if you can reproduce the issue then I'm sure Unity would like to hear about it

**Comment by AAverin** [comment]
Funny enough, I now can't remove StateEngine component form my gameobject - Unity says my object depends on it and doesn't let to remove

**Comment by thefuntastic** [comment]
So RequireComponent has a quirk, that if you change the type of the script 
`MyStateBehaviour : MonoBehaviour ` to `MyStateBehaviour : StateBehaviour ` after it has been added to the game object, RequireComponent doesn't execute. However if this is done before adding the script to the component RequireComponent will correctly fill the dependency and add the StateEngine script as well. 

Since I originally wrote the library, I've learnt that managing this through AddComponent in the StateBehaviour class is a more dependable strategy. It's been added to the list of things I need to look into next time I get a chance to pay this project some dedicated attention, or would be a fairly simple pull request if anyone else wants to tackle it.

**Comment by AAverin** [comment]
I see, thanks.
I will be playing around with library for my personal project, and will make a pull request after I feel confident enough with Unity and C# in general - I've just started.
For now I'll be just adding StateEngine directly to my GameObjects just to be sure.
