### ISSUE TITLE
State does not run exit after entering state a second time in Unity 5.6

### ISSUE THREAD

**Issue by ttay24** [thefuntastic/Unity3d-Finite-State-Machine#26]
I'm not sure if this is a result of this version of Unity, or what, but I've noticed an issue now that I did not have previously.

My states go as follows:
Main Menu -> Loading Level -> In Game -> Paused (then quit game) -> Main Menu 

I'm trying to go to loading level again, but it's trying to do a safe transition from Main Menu. Any clue what could be the problem? Sorry, I know it's vague. Let me know if I need to provide more info

**Comment by thefuntastic** [comment]
Uh, it's pretty hard to offer much advice based on that. 

If you're quitting, are you loading a new scene? The statemachine is tied to the life cycle of a game object. So if your game object gets destroyed, so will the state machine? Otherwise it would help to know exactly where it's failing. Do you know how to use a debugger? Step through the code every time you call ChangeState, even if you don't quite understand what's going on in the StateMachine class, it should allow you to see whats different when it's not working as you expect.
